language: java

dist: trusty
sudo: required

jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}

install:
# Build powsybl-core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- pushd powsybl/powsybl-core && mvn --batch-mode -DskipTests install && popd
# Build powsybl-open-loadflow
- git clone https://github.com/powsybl/powsybl-open-loadflow powsybl/powsybl-open-loadflow
- pushd powsybl/powsybl-open-loadflow && mvn --batch-mode -DskipTests install && popd

script:
- mvn --batch-mode -Pjacoco,checks clean verify sonar:sonar
