componentDefaultConfig:
    LoadFlowFactory: com.rte_france.powsybl.hades2.Hades2Factory
    SecurityAnalysisFactory: com.rte_france.powsybl.hades2.Hades2SecurityAnalysisFactory
    ContingenciesProviderFactory: com.powsybl.action.dsl.GroovyDslContingenciesProviderFactory
    
computation-local:
    localDir: /usr/hades/temp
    availableCore: 1

hades2:
  homeDir: /usr/hades/
  timeout: 120
  debug: true
  useSAX: false
  