#
# Copyright (c) 2022, Jean-Baptiste Heyberger & Geoffroy Jamgotchian
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# query: synchronousMachineShortCircuit
SELECT *
{
    ?ID
        a cim:SynchronousMachine ;
    OPTIONAL { ?ID cim:SynchronousMachine.satDirectSubtransX ?satDirectSubtransX }
    OPTIONAL { ?ID cim:SynchronousMachine.satDirectTransX ?satDirectTransX }
    OPTIONAL { ?ID cim:SynchronousMachine.r0 ?r0 }
    OPTIONAL { ?ID cim:SynchronousMachine.r2 ?r2 }
    OPTIONAL { ?ID cim:SynchronousMachine.x0 ?x0 }
    OPTIONAL { ?ID cim:SynchronousMachine.x2 ?x2 }
    OPTIONAL { ?ID cim:SynchronousMachine.r ?r }
    OPTIONAL { ?ID cim:SynchronousMachine.shortCircuitRotorType ?shortCircuitRotorType }
    OPTIONAL { ?ID cim:RotatingMachine.ratedU ?ratedU }
}
